// tailwind.config.ts
import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                // Mapped dari CSS variables di login.html
                bg: "#0d0f14",
                surface: "#151820",
                surface2: "#1c2030",
                border: "#252a3a",
                accent: "#4f8cff",
                accent2: "#a78bfa",
                green: "#34d399",
                red: "#f87171",
                yellow: "#fbbf24",
                text: "#e8eaf2",
                muted: "#6b7290",
                // ── Material Design 3 Tokens (dari HTML asli) ──────────
                "on-error":                    "#690005",
                "on-secondary-fixed-variant":  "#4f319c",
                "surface-container-high":      "#282a2f",
                "tertiary":                    "#45dfa4",
                "on-surface-variant":          "#c2c6d6",
                "on-primary":                  "#002d6c",
                "on-background":               "#e2e2e9",
                "outline-variant":             "#424753",
                "on-tertiary-container":       "#003120",
                "inverse-surface":             "#e2e2e9",
                "surface-container-lowest":    "#0c0e13",
                "tertiary-fixed":              "#68fcbf",
                "status-warning":              "#fbbf24",
                "surface-bright":              "#37393f",
                "on-tertiary-fixed-variant":   "#005137",
                "on-tertiary":                 "#003825",
                "surface-container-low":       "#1a1b21",
                "status-error":                "#f87171",
                "tertiary-container":          "#00a574",
                "primary":                     "#afc6ff",
                "secondary-container":         "#4f319c",
                "secondary":                   "#cebdff",
                "surface-dim":                 "#111318",
                "error-container":             "#93000a",
                "on-secondary":                "#381385",
                "surface-elevated":            "#1c2030",
                "text-muted":                  "#6b7290",
                "inverse-on-surface":          "#2e3036",
                "primary-fixed-dim":           "#afc6ff",
                "inverse-primary":             "#0059c6",
                "surface-container":           "#1e1f25",
                "surface-main":                "#151820",
                "outline":                     "#8c909f",
                "surface-container-highest":   "#33353a",
                "secondary-fixed-dim":         "#cebdff",
                "error":                       "#ffb4ab",
                "on-secondary-container":      "#bea8ff",
                "on-primary-fixed-variant":    "#004398",
                "surface-variant":             "#33353a",
                "on-secondary-fixed":          "#21005e",
                "on-surface":                  "#e2e2e9",
                "tertiary-fixed-dim":          "#45dfa4",
                "text-primary":                "#e8eaf2",
                "on-primary-fixed":            "#001a43",
                "primary-fixed":               "#d9e2ff",
                "secondary-fixed":             "#e8ddff",
                "background":                  "#111318",
                "on-error-container":          "#ffdad6",
                "surface-tint":                "#afc6ff",
                "border-subtle":               "#252a3a",
                "on-tertiary-fixed":           "#002114",
                "on-primary-container":        "#00275f",
                "primary-container":           "#528dff",
            },
            spacing: {
                "internal-gap":       "8px",
                "gutter":             "16px",
                "container-padding":  "28px",
                "component-padding":  "20px",
                "drawer-width":       "340px",
                "section-gap":        "20px",
                "sidebar-width":      "280px",
            },
            fontFamily: {
                syne: ["Syne", "sans-serif"],
                dm: ["DM Sans", "sans-serif"],
                "body-large":             ["DM Sans", "sans-serif"],
                "button-text":            ["Syne", "sans-serif"],
                "headline-modal-mobile":  ["Syne", "sans-serif"],
                "helper-text":            ["DM Sans", "sans-serif"],
                "display-brand":          ["Syne", "sans-serif"],
                "stat-value":             ["Syne", "sans-serif"],
                "body-chat":              ["DM Sans", "sans-serif"],
                "section-label":          ["DM Sans", "sans-serif"],
                "headline-modal":         ["Syne", "sans-serif"],
            },
            fontSize: {
                "body-large":            ["15px", { lineHeight: "1.6",  fontWeight: "400" }],
                "button-text":           ["15px", { lineHeight: "1.0",  fontWeight: "700" }],
                "headline-modal-mobile": ["18px", { lineHeight: "1.4",  fontWeight: "700" }],
                "helper-text":           ["13px", { lineHeight: "1.4",  fontWeight: "400" }],
                "display-brand":         ["22px", { lineHeight: "1.2",  letterSpacing: "-0.02em", fontWeight: "800" }],
                "stat-value":            ["15px", { lineHeight: "1.0",  fontWeight: "700" }],
                "body-chat":             ["14px", { lineHeight: "1.6",  fontWeight: "400" }],
                "section-label":         ["11px", { lineHeight: "1.0",  letterSpacing: "1.2px",  fontWeight: "600" }],
                "headline-modal":        ["20px", { lineHeight: "1.4",  fontWeight: "700" }],
            },

            borderRadius: {
                card: "24px",
                btn: "12px",
                input: "10px",
            },
            keyframes: {
                cardIn: {
                    from: { opacity: "0", transform: "translateY(24px) scale(0.98)" },
                    to: { opacity: "1", transform: "translateY(0) scale(1)" },
                },
                fadeUp: {
                    from: { opacity: "0", transform: "translateY(8px)" },
                    to: { opacity: "1", transform: "translateY(0)" },
                },
                spin: {
                    to: { transform: "rotate(360deg)" },
                },
                orbFloat1: {
                    "0%, 100%": { transform: "translate(0, 0)" },
                    "50%": { transform: "translate(40px, 30px)" },
                },
                orbFloat2: {
                    "0%, 100%": { transform: "translate(0, 0)" },
                    "50%": { transform: "translate(-30px, -40px)" },
                },
                fadeIn: {
                    from: { opacity: "0", transform: "translateY(8px)" },
                    to: { opacity: "1", transform: "translateY(0)" }
                },
                pulse: {
                    "0%,100%": { transform: "scale(1)" },
                    "50%": { transform: "scale(1.05)" }
                },
                slideUp: {
                    from: { transform: "translateY(100%)" },
                    to: { transform: "translateY(0)" }
                },
                waveform: {
                    "0%,100%": { transform: "scaleY(0.4)" },
                    "50%": { transform: "scaleY(1)" }
                },
            },
            animation: {
                "card-in": "cardIn 0.5s cubic-bezier(0.22, 1, 0.36, 1) both",
                "fade-up": "fadeUp 0.25s ease both",
                "spin-fast": "spin 0.6s linear infinite",
                "orb-float1": "orbFloat1 12s ease-in-out infinite",
                "orb-float2": "orbFloat2 15s ease-in-out infinite",
                "fade-in": "fadeIn 0.3s ease forwards",
                "spin-slow": "spin 1s linear infinite",
                "pulse-mic": "pulse 1.5s ease-in-out infinite",
                "slide-up": "slideUp 0.3s ease",
                "wave": "waveform 1.2s ease-in-out infinite",
            },
            boxShadow: {
                "accent-glow": "0 0 12px #4f8cff",
                "btn-hover": "0 4px 20px rgba(79, 140, 255, 0.3)",
                "tab-active": "0 1px 4px rgba(0,0,0,0.3)",
                "focus-ring": "0 0 0 3px rgba(79, 140, 255, 0.12)",
                "accent2-glow": "0 0 12px #a78bfa",
                "green-glow": "0 0 12px #34d399",
                "red-glow": "0 0 12px #f87171",
            },
        },
    },
    plugins: [],
};

export default config;